// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLWWHbA16WoXal6xZnB0HzCwPNfo2AcXE',
    appId: '1:888263516269:web:397fd57e8add406b025f64',
    messagingSenderId: '888263516269',
    projectId: 'minnano-app',
    authDomain: 'minnano-app.firebaseapp.com',
    storageBucket: 'minnano-app.firebasestorage.app',
    measurementId: 'G-90R6986EK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmvyv07eQPoXQqY51pdFIaBygdRljHAsA',
    appId: '1:888263516269:android:e29d090f2e938c0b025f64',
    messagingSenderId: '888263516269',
    projectId: 'minnano-app',
    storageBucket: 'minnano-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPI7oQkY2_ZAa5BBX5dC68ZP1LELmtXC8',
    appId: '1:888263516269:ios:4c3bf4fb634df9c6025f64',
    messagingSenderId: '888263516269',
    projectId: 'minnano-app',
    storageBucket: 'minnano-app.firebasestorage.app',
    iosBundleId: 'app.boook24.minnanoReviewApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPI7oQkY2_ZAa5BBX5dC68ZP1LELmtXC8',
    appId: '1:888263516269:ios:4c3bf4fb634df9c6025f64',
    messagingSenderId: '888263516269',
    projectId: 'minnano-app',
    storageBucket: 'minnano-app.firebasestorage.app',
    iosBundleId: 'app.boook24.minnanoReviewApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLWWHbA16WoXal6xZnB0HzCwPNfo2AcXE',
    appId: '1:888263516269:web:6417db5e0e713ec3025f64',
    messagingSenderId: '888263516269',
    projectId: 'minnano-app',
    authDomain: 'minnano-app.firebaseapp.com',
    storageBucket: 'minnano-app.firebasestorage.app',
    measurementId: 'G-J5F7Y3YTTW',
  );
}